### ISSUE TITLE
Improvements in timezone support #2

### ISSUE THREAD

**Issue by filimonov** [yandex/ClickHouse#1298]
1) For international market support of fractional timezone offsets is mandatory. (Don't you have any installations in India yet?)
2) It would be nice to have an ability to pass timezone dynamically. At that moment if you try to do something like 
`select toString(timestamp, dictGetString('timezones', 'tz_name', toUInt64(counterid)) ) from table;`
You get the following error:
```
Received exception from server:
Code: 44. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Illegal column ColumnString of second (time zone) argument of function, must be constant string. 
```
Why needed: data from multiple timezones need to be agregated on daily base (days limit differs in different timezones). Of course select can be split to multiple selects (and may be it will even give a better performance), but it would be better to have such a possibility to make a timezone magic on DB side.

**Comment by silviucpp** [comment]
This seems fixed in last master in commit 4236bcbfa2365faf569b12cde64e6bf62d17517a

**Comment by silviucpp** [comment]
@alexey-milovidov  can confirm that this was fixed

**Comment by alexey-milovidov** [comment]
Now we have support for timezones with fractional offset from UTC.

* Known minor issue: if you have timezone with fractional offset, and the fraction was changed sometimes (there are not much: Lord Howe Island, Pacific/Pitcairn), then the function `toRelativeHourNum` will give incorrect result.

We still don't have support to use non-constant time zone parameter in functions; to parse DateTime with explicitly specified offset or time zone.

**Comment by silviucpp** [comment]
@alexey-milovidov having support for offsets is not so important as @filimonov pointed there are simple alternatives for this like:

```sql
select count(*) as count, toRelativeDayNum(date+3*3600) - toRelativeDayNum(X+3*3600) from table
when date >= X and date =< Y
```

Probably we can close this bug

**Comment by alexey-milovidov** [comment]
Ok.
