### ISSUE TITLE
INSERT FORMAT TabSeparatedWithNames not worked for Array(String) type and empty [''] value

### ISSUE THREAD

**Issue by Slach** [yandex/ClickHouse#1420]
I have following database structure https://gist.github.com/Slach/58bd50dd4f7789e981fa3cfb7cdea1fe#file-create-sql

I try INSERT following TSV data https://gist.github.com/Slach/58bd50dd4f7789e981fa3cfb7cdea1fe#file-metrika_visits-0-tsv

over following shell script
https://gist.github.com/Slach/58bd50dd4f7789e981fa3cfb7cdea1fe#file-error-sh

but see following error
https://gist.github.com/Slach/58bd50dd4f7789e981fa3cfb7cdea1fe#file-error-output

on GoalsOrder field value
```
['']
```

when i try to insert simple empty value over http or over native client with using following bash script, data inserted OK
```
echo -ne "Date\tGoalsOrder\n2017-10-18\t['']" | curl -vvv -XPOST -H "Content-type: text/plain" --data-binary @- "http://localhost:8123/?query=INSERT+INTO+metrika2clickhouse.metrika_visits_local(Date,GoalsOrder)+FORMAT+TabSeparatedWithNames"

echo -ne "Date\tGoalsOrder\n2017-11-18\t['']" | clickhouse-client --echo -q "INSERT INTO metrika2clickhouse.metrika_visits_local(Date,GoalsOrder) FORMAT TabSeparatedWithNames"
INSERT INTO metrika2clickhouse.metrika_visits_local(Date,GoalsOrder) FORMAT TabSeparatedWithNames
```

could you fix TSV \ CSV parser in clickhouse for my case ?

**Comment by filimonov** [comment]
you've messed something in the steps to reproduce. You provided create statement for table 
metrika_hits_local (incorrect one, it has two BrowserEngine columns). And you are trying to insert into table metrika_visits_local with other fields.

On the subject: use double quotes for quoting string in arrays. So instead of [''] use [""]. It should solve the problem.

That quoting rules are not too clear, but you can always look on the clickhouse output to undersatnd what he expect as an input.

**Comment by Slach** [comment]
i update CREATE TABLE on my gist

> That quoting rules are not too clear, but you can always look on the clickhouse output to undersatnd what he expect as an input.
hmm ;) but clickhouse-client output look like [''] for empty Array(String) field

pls see https://gist.github.com/Slach/58bd50dd4f7789e981fa3cfb7cdea1fe#file-clickhouse-client-output-tabseparatedwithnames-md

i use latest Clickhouse package (clickhouse-server-common is already the newest version (1.1.54304).)

**Comment by filimonov** [comment]
>  but clickhouse-client output look like [''] for empty Array(String) field
Yes, you're right, sorry. 

Now the table definition is ok, but i can't reproduce the bug. Tryed 1.1.54289 and 1.1.54304 and both work correctly with your sample. :-/

**Comment by Slach** [comment]
i'm update my gist 
https://gist.github.com/Slach/58bd50dd4f7789e981fa3cfb7cdea1fe
and error still reproduce
i add Vagrantfile

just run following command for reproduce
```
git clone https://gist.github.com/Slach/58bd50dd4f7789e981fa3cfb7cdea1fe
cd 58bd50dd4f7789e981fa3cfb7cdea1fe
vagrant up --provision
```

**Comment by filimonov** [comment]
Yes. With that source file i get the error - reproducable without vagrant and virtualization. 

But, it's not only ClickHouse see the error in that position of your input file.
You have there something like that: 
78	Russia	[]	[]	0	[]	[,]	[]	

If you will replace [,] to ['',''] it will work. ;-)

**Comment by alexey-milovidov** [comment]
Filimonov, thank you!

Slach:
If you have exported this data from Yandex.Metrika Logs API, please file an issue to them.
