### ISSUE TITLE
broken build with USE_STATIC_LIBRARIES=FALSE

### ISSUE THREAD

**Issue by chipitsine** [yandex/ClickHouse#238]
https://github.com/yandex/ClickHouse/blob/master/libs/libmysqlxx/CMakeLists.txt#L37

variable MYSQLCLIENT_LIB is set _only_ when USE_STATIC_LIBRARIES=TRUE, so it fails otherwise:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MYSQLCLIENT_LIB
    linked by target "mysqlxx" in directory /root/clickhouse/libs/libmysqlxx
```

**Comment by proller** [comment]
looks like it was fixed here https://github.com/yandex/ClickHouse/commit/ca5c1dc31baca3c4645a6322e03e0224a2cd3258

by calling include (cmake/find_libmysqlclient.cmake) with library find

@chipitsine can you try build now with fresh master ?

**Comment by chipitsine** [comment]
I'll test soon, stay tuned

**Comment by chipitsine** [comment]
something else is still broken

```
[ilia@localhost ClickHouse]$ cmake .
-- CMAKE_BUILD_TYPE is not set, set to default = RELWITHDEBINFO
-- CMAKE_BUILD_TYPE: RELWITHDEBINFO
-- Tests are enabled
-- Poco package version: 1.6.1-all (2015-08-04)
-- Setting Poco build type - RELWITHDEBINFO
-- Building static libraries
-- Building without tests & samples
-- Build with using internal copy of sqlite, pcre, expat, ...
-- ODBC Support Enabled
-- CMake 3.6.2 successfully configured Poco using Unix Makefiles generator
-- Installation target path: /usr
-- Building: XML
-- Building: MongoDB
-- Building: Util
-- Building: Net
-- Building: NetSSL_OpenSSL
-- Building: Crypto
-- Building: Data
-- Building: Zip
-- ZSTD VERSION 1.1.1024
-- Architecture: x86_64
-- Architecture-specific source files: arch/x86/x86.c;arch/x86/insert_string_sse.c;arch/x86/fill_window_sse.c
-- Building: tcmalloc_minimal_internal
-- Link libtcmalloc_minimal
-- Not using any library for line editing.
-- C_FLAGS:  =-fno-omit-frame-pointer -Wall -Werror -msse4 -mpopcnt  -D_GLIBCXX_USE_CXX11_ABI=1
-- CXX_FLAGS:=-std=gnu++1y  -fno-omit-frame-pointer -Wall -Werror -Wnon-virtual-dtor -msse4 -mpopcnt  -D_GLIBCXX_USE_CXX11_ABI=1
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ICUDATA
    linked by target "common" in directory /home/ilia/ClickHouse/libs/libcommon
    linked by target "date_lut3" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
    linked by target "date_lut_init" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
    linked by target "date_lut2" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
    linked by target "date_lut4" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
ICUI18N
    linked by target "common" in directory /home/ilia/ClickHouse/libs/libcommon
    linked by target "date_lut3" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
    linked by target "date_lut_init" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
    linked by target "date_lut2" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
    linked by target "date_lut4" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
ICUUC
    linked by target "common" in directory /home/ilia/ClickHouse/libs/libcommon
    linked by target "date_lut3" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
    linked by target "date_lut_init" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
    linked by target "date_lut2" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
    linked by target "date_lut4" in directory /home/ilia/ClickHouse/libs/libcommon/src/tests
LTDL_LIB
    linked by target "dbms" in directory /home/ilia/ClickHouse/dbms

-- Configuring incomplete, errors occurred!
See also "/home/ilia/ClickHouse/CMakeFiles/CMakeOutput.log".
See also "/home/ilia/ClickHouse/CMakeFiles/CMakeError.log".
```

**Comment by chipitsine** [comment]
I still see "set (MYSQLCLIENT_LIB ${CMAKE_CURRENT_BINARY_DIR}/libmysqlclient.a)" inside "if" and there's nothing like that in "else"

https://github.com/yandex/ClickHouse/blob/master/libs/libmysqlxx/CMakeLists.txt#L32-Lundefined


so,

```
[ilia@localhost ClickHouse]$ cmake .
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is not set, set to default = RELWITHDEBINFO
-- CMAKE_BUILD_TYPE: RELWITHDEBINFO
-- Tests are enabled
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2j") 
-- Poco package version: 1.6.1-all (2015-08-04)
-- Setting Poco build type - RELWITHDEBINFO
-- Building static libraries
-- Building without tests & samples
-- Build with using internal copy of sqlite, pcre, expat, ...
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test HAVE_GETADDRINFO_A
-- Performing Test HAVE_GETADDRINFO_A - Success
-- Found ODBC: /usr/include  
-- ODBC Support Enabled
-- CMake 3.6.2 successfully configured Poco using Unix Makefiles generator
-- Installation target path: /usr
-- Building: XML
-- Building: MongoDB
-- Building: Util
-- Building: Net
-- Building: NetSSL_OpenSSL
-- Building: Crypto
-- Building: Data
-- Building: Zip
-- ZSTD VERSION 1.1.1024
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Architecture: x86_64
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for stdarg.h
-- Looking for stdarg.h - found
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_HIDDEN
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_HIDDEN - Success
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_INTERNAL
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_INTERNAL - Success
-- Performing Test HAVE_BUILTIN_CTZL
-- Performing Test HAVE_BUILTIN_CTZL - Success
-- Performing Test HAVE_SSE2_INTRIN
-- Performing Test HAVE_SSE2_INTRIN - Success
-- Performing Test HAVE_SSE42_INTRIN
-- Performing Test HAVE_SSE42_INTRIN - Success
-- Performing Test HAVE_PCLMULQDQ_INTRIN
-- Performing Test HAVE_PCLMULQDQ_INTRIN - Failed
-- Architecture-specific source files: arch/x86/x86.c;arch/x86/insert_string_sse.c;arch/x86/fill_window_sse.c
-- Building: tcmalloc_minimal_internal
-- Link libtcmalloc_minimal
-- Using line editing libraries: /usr/lib64/libreadline.so;/usr/lib64/libtermcap.so
-- C_FLAGS:  =-fno-omit-frame-pointer -Wall -Werror -msse4 -mpopcnt  -D_GLIBCXX_USE_CXX11_ABI=1
-- CXX_FLAGS:=-std=gnu++1y  -fno-omit-frame-pointer -Wall -Werror -Wnon-virtual-dtor -msse4 -mpopcnt  -D_GLIBCXX_USE_CXX11_ABI=1
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MYSQLCLIENT_LIB
    linked by target "mysqlxx" in directory /home/ilia/ClickHouse/libs/libmysqlxx

-- Configuring incomplete, errors occurred!
See also "/home/ilia/ClickHouse/CMakeFiles/CMakeOutput.log".
See also "/home/ilia/ClickHouse/CMakeFiles/CMakeError.log".
```


bug is still there

**Comment by proller** [comment]
mysqlclient finding here:  
https://github.com/yandex/ClickHouse/blob/master/cmake/find_libmysqlclient.cmake#L6

Did you install libmysqlclient-dev ?

What OS you use ?

can you add line to end of master/cmake/find_libmysqlclient.cmake:
```
message (STATUS "mysqlclient found: MYSQLCLIENT_LIB=${MYSQLCLIENT_LIB} MYSQL_INCLUDE_DIR=${MYSQL_INCLUDE_DIR} STATIC_MYSQLCLIENT_LIB=${STATIC_MYSQLCLIENT_LIB}")
```
and show output ?

**Comment by chipitsine** [comment]
```
[root@localhost ilia]# ls /usr/lib64/mysql/libmysqlclient*
/usr/lib64/mysql/libmysqlclient.a     /usr/lib64/mysql/libmysqlclient.so.18
/usr/lib64/mysql/libmysqlclient_r.so  /usr/lib64/mysql/libmysqlclient.so.18.0.0
/usr/lib64/mysql/libmysqlclient.so
[root@localhost ilia]# 
```

```
[ilia@localhost ~]$ rpm -qa | grep mysql
mysql++-3.2.2-4.fc24.x86_64
mysql++-devel-3.2.2-4.fc24.x86_64
[ilia@localhost ~]$ rpm -qa | grep mariadb
mariadb-embedded-devel-10.1.19-1.fc25.x86_64
mariadb-config-10.1.19-1.fc25.x86_64
mariadb-devel-10.1.19-1.fc25.x86_64
mariadb-libs-10.1.19-1.fc25.x86_64
mariadb-embedded-10.1.19-1.fc25.x86_64
mariadb-errmsg-10.1.19-1.fc25.x86_64
mariadb-common-10.1.19-1.fc25.x86_64
[ilia@localhost ~]$ 
```

```
[root@localhost ilia]# dnf search libmysqlclient-dev
Last metadata expiration check: 5:35:12 ago on Thu Jan 12 09:21:50 2017.
Error: No matches found.
[root@localhost ilia]# 
```

Fedora 25

after adding the above line:

```
[ilia@localhost ClickHouse]$ export USE_STATIC_LIBRARIES=FALSE
[ilia@localhost ClickHouse]$ cmake .
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is not set, set to default = RELWITHDEBINFO
-- CMAKE_BUILD_TYPE: RELWITHDEBINFO
-- Tests are enabled
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2j") 
-- mysqlclient found: MYSQLCLIENT_LIB=MYSQLCLIENT_LIB-NOTFOUND MYSQL_INCLUDE_DIR=/usr/include/mysql STATIC_MYSQLCLIENT_LIB=
-- Poco package version: 1.6.1-all (2015-08-04)
-- Setting Poco build type - RELWITHDEBINFO
-- Building static libraries
-- Building without tests & samples
-- Build with using internal copy of sqlite, pcre, expat, ...
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test HAVE_GETADDRINFO_A
-- Performing Test HAVE_GETADDRINFO_A - Success
-- Found ODBC: /usr/include  
-- ODBC Support Enabled
-- CMake 3.6.2 successfully configured Poco using Unix Makefiles generator
-- Installation target path: /usr
-- Building: XML
-- Building: MongoDB
-- Building: Util
-- Building: Net
-- Building: NetSSL_OpenSSL
-- Building: Crypto
-- Building: Data
-- Building: Zip
-- ZSTD VERSION 1.1.1024
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Architecture: x86_64
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for stdarg.h
-- Looking for stdarg.h - found
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_HIDDEN
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_HIDDEN - Success
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_INTERNAL
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_INTERNAL - Success
-- Performing Test HAVE_BUILTIN_CTZL
-- Performing Test HAVE_BUILTIN_CTZL - Success
-- Performing Test HAVE_SSE2_INTRIN
-- Performing Test HAVE_SSE2_INTRIN - Success
-- Performing Test HAVE_SSE42_INTRIN
-- Performing Test HAVE_SSE42_INTRIN - Success
-- Performing Test HAVE_PCLMULQDQ_INTRIN
-- Performing Test HAVE_PCLMULQDQ_INTRIN - Failed
-- Architecture-specific source files: arch/x86/x86.c;arch/x86/insert_string_sse.c;arch/x86/fill_window_sse.c
-- Building: tcmalloc_minimal_internal
-- Link libtcmalloc_minimal
-- Using line editing libraries: /usr/lib64/libreadline.so;/usr/lib64/libtermcap.so
-- C_FLAGS:  =-fno-omit-frame-pointer -Wall -Werror -msse4 -mpopcnt  -D_GLIBCXX_USE_CXX11_ABI=1
-- CXX_FLAGS:=-std=gnu++1y  -fno-omit-frame-pointer -Wall -Werror -Wnon-virtual-dtor -msse4 -mpopcnt  -D_GLIBCXX_USE_CXX11_ABI=1
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MYSQLCLIENT_LIB
    linked by target "mysqlxx" in directory /home/ilia/ClickHouse/libs/libmysqlxx

-- Configuring incomplete, errors occurred!
See also "/home/ilia/ClickHouse/CMakeFiles/CMakeOutput.log".
See also "/home/ilia/ClickHouse/CMakeFiles/CMakeError.log".
[ilia@localhost ClickHouse]$ 

```

**Comment by proller** [comment]
https://github.com/yandex/ClickHouse/commit/4bfa69765650afcc3345ef1600da63e50918b1c1

Please update and try again

**Comment by sangli00** [comment]
how to fixed 
```-- Performing Test HAVE_PCLMULQDQ_INTRIN - Failed```
