### ISSUE TITLE
Kafka engine creates duplicate records

### ISSUE THREAD

**Issue by bespilotnayakartoshka** [yandex/ClickHouse#6661]
**Describe the bug**
Currently i have setup like this: 
2 shards 2 replicas each 

I have an table with kafka engine on each instance (for example, kafka_table). Settings are made correct with same consumer group to avoid dups as it described in docs. 
Then i have MV which takes records from kafka_table.
Then i have a table named `my_super_table` which takes records from MV 

So now we have 4 consumers at all.

And during push something to kafka i have randomly duplicate records. They became on different or same shard. It looks like magic. 

I fully check whats really kafka contains and there are no dups in it. 

* Which ClickHouse server version to use
19.13, 19.11, 19.8, 19.6

**Expected behavior**
There are no any duplicates. 

**Error message and/or stacktrace**
There are no any errors in log also. 

---------- 

Is there a stable version with kafka engine ?

**Comment by josepowera** [comment]
There were some fixes for Kafka on 19.13 released only 4 days ago... 
For debugging what is happening also try to add to destination table Kafka virtual columns for offset and partition.

**Comment by filimonov** [comment]
Not enough information to reproduce the issue :\ 

At least you should try to enable kafka debug logging 
```xml
<!-- add it to config.xml -->
<kafka>
    <debug>all</debug>
</kafka>
```
and send the fragment of logs in /var/log/clickhouse-server.log when duplicate happens.
 
Ideally - if you will be able to show reproduce issue using docker / docker-compose (like here: https://github.com/yandex/ClickHouse/pull/6365/files

There is known bug (is being debugged / fixed currently) when duplicates appear the clickhouse node restarts: #6414 . Maybe your case is somehow related. 

In general: in some very extreme cases (like network disconnects / power failure etc) duplicates can be expected, as ClickHouse works with Kafka in 'at-least-once' model, but of course during normal operations no duplicates should appear. 

> Is there a stable version with kafka engine ?

19.11.8 and 19.13.3 are the most stable from 19.x branch. You can also try 18.14.

PS. Exactly once can be confidered only after rdkafka will implement that, see / upvote: https://github.com/edenhill/librdkafka/issues/1308

**Comment by bespilotnayakartoshka** [comment]
@filimonov thanks for the answer :) 

this issue is reproduced on cluster in docker also with the same versions above  
I will try to reproduce and send logs, thanks :) 

@josepowera Yes, i saw those fixes in changelog, but it has much more dups as lower versions 

on 10kk messages it was like 10% of dups on 19.13 
and it was only 100 on 19.6

**Comment by bl17zar** [comment]
Hello, it's some kind of magic, but I just wanted to create the same issue, cause I have the same problem, and found no answers in google, and found this issue created only 3 hours ago.

I prepared logs as you asked @bespilotnayakartoshka. I have the simplest setup:
https://hub.docker.com/r/yandex/clickhouse-server
https://hub.docker.com/r/spotify/kafka

Everything runs on one node with default configs.

I created topic in kafka, populated it with 10 messages. Then I created clickhouse table with engine Kafka and corresponding MV like this:

```sql

    CREATE TABLE event_1 (
        ts UInt64,
        uid_1 String,
        message String
    ) ENGINE = Kafka('localhost:9092', 'test.event_1', 'test', 'JSONEachRow');

    CREATE TABLE event_1_crm (
        ts UInt64,
        uid_1 String,
        message String,
        crm_id UUID
    ) ENGINE = MergeTree()
    PARTITION BY toDate(toDateTime(ts))
    ORDER BY (ts);

    CREATE MATERIALIZED VIEW consumer_1 TO event_1_crm
    AS SELECT ts, uid_1, message, generateUUIDv4() AS crm_id FROM event_1;

```

When I count() on event_1 table it gives me 10, as expected every time. But when I count() on event_1_crm table it gives me every time monotonously incrementing int % 10 == 0.

Here are the logs where it constantly reads the same batch from kafka, like it doesn't know the last commit value. 

```
2019.08.26 10:24:06.488680 [ 40 ] {} <Debug> default.event_1_crm (MergerMutator): Merge sorted 2490 rows, containing 4 columns (4 merged, 0 gathered) in 0.01 sec., 493042.46 rows/sec., 29.09 MB/sec.             
2019.08.26 10:24:06.489645 [ 40 ] {} <Trace> default.event_1_crm: Renaming temporary part tmp_merge_20190826_1_249_49 to 20190826_1_249_49.                                                                        
2019.08.26 10:24:06.489877 [ 40 ] {} <Trace> default.event_1_crm (MergerMutator): Merged 6 parts: from 20190826_1_244_48 to 20190826_249_249_0                                                                     
2019.08.26 10:24:06.982549 [ 9 ] {} <Debug> StorageKafka (event_1): Started streaming to 1 attached views                                                                                                          
2019.08.26 10:24:06.983354 [ 9 ] {} <Trace> StorageKafka (event_1): Subscribed to topics: test.event_1                                                                                                             
2019.08.26 10:24:06.983578 [ 9 ] {} <Trace> StorageKafka (event_1): Assigned to topics: test.event_1                                                                                                               
2019.08.26 10:24:07.484095 [ 9 ] {} <Trace> StorageKafka (event_1): Polled batch of 10 messages                                                                                                                    
2019.08.26 10:24:07.984494 [ 9 ] {} <Trace> StorageKafka (event_1): Stalled                                                                                                                                        
2019.08.26 10:24:07.986328 [ 9 ] {} <Trace> StorageKafka (event_1): Committed offset 20 (topic: test.event_1, partition: 0)                                                                                        
2019.08.26 10:24:07.987256 [ 9 ] {} <Trace> InterpreterSelectQuery: FetchColumns -> Complete                                                                                                                       
2019.08.26 10:24:07.988776 [ 9 ] {} <Trace> default.event_1_crm: Renaming temporary part tmp_insert_20190826_250_250_0 to 20190826_250_250_0.                                                                      
2019.08.26 10:24:07.989086 [ 9 ] {} <Trace> StorageKafka (event_1): Execution took 1006 ms.                                                                                                                        
2019.08.26 10:24:08.489324 [ 20 ] {} <Debug> StorageKafka (event_1): Started streaming to 1 attached views                                                                                                         
2019.08.26 10:24:08.490123 [ 20 ] {} <Trace> StorageKafka (event_1): Subscribed to topics: test.event_1                                                                                                            
2019.08.26 10:24:08.490334 [ 20 ] {} <Trace> StorageKafka (event_1): Assigned to topics: test.event_1                                                                                                              
2019.08.26 10:24:08.990984 [ 20 ] {} <Trace> StorageKafka (event_1): Polled batch of 10 messages                                                                                                                   
2019.08.26 10:24:09.491376 [ 20 ] {} <Trace> StorageKafka (event_1): Stalled                                                                                                                                       
2019.08.26 10:24:09.492536 [ 20 ] {} <Trace> StorageKafka (event_1): Committed offset 20 (topic: test.event_1, partition: 0)                                                                                      
2019.08.26 10:24:09.493040 [ 20 ] {} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2019.08.26 10:24:09.493874 [ 20 ] {} <Trace> default.event_1_crm: Renaming temporary part tmp_insert_20190826_251_251_0 to 20190826_251_251_0.                                                                    
2019.08.26 10:24:09.494040 [ 20 ] {} <Trace> StorageKafka (event_1): Execution took 1004 ms.
2019.08.26 10:24:09.994301 [ 6 ] {} <Debug> StorageKafka (event_1): Started streaming to 1 attached views
2019.08.26 10:24:09.995013 [ 6 ] {} <Trace> StorageKafka (event_1): Subscribed to topics: test.event_1
2019.08.26 10:24:09.995135 [ 6 ] {} <Trace> StorageKafka (event_1): Assigned to topics: test.event_1
2019.08.26 10:24:10.495554 [ 6 ] {} <Trace> StorageKafka (event_1): Polled batch of 10 messages
2019.08.26 10:24:10.995972 [ 6 ] {} <Trace> StorageKafka (event_1): Stalled
2019.08.26 10:24:10.997722 [ 6 ] {} <Trace> StorageKafka (event_1): Committed offset 20 (topic: test.event_1, partition: 0)                                                                                       
2019.08.26 10:24:10.998648 [ 6 ] {} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2019.08.26 10:24:11.000267 [ 6 ] {} <Trace> default.event_1_crm: Renaming temporary part tmp_insert_20190826_252_252_0 to 20190826_252_252_0.                                                                     
2019.08.26 10:24:11.000580 [ 6 ] {} <Trace> StorageKafka (event_1): Execution took 1006 ms.
2019.08.26 10:24:11.500841 [ 22 ] {} <Debug> StorageKafka (event_1): Started streaming to 1 attached views                                                                                                        
2019.08.26 10:24:11.501635 [ 22 ] {} <Trace> StorageKafka (event_1): Subscribed to topics: test.event_1
2019.08.26 10:24:11.501838 [ 22 ] {} <Trace> StorageKafka (event_1): Assigned to topics: test.event_1
2019.08.26 10:24:12.002457 [ 22 ] {} <Trace> StorageKafka (event_1): Polled batch of 10 messages
2019.08.26 10:24:12.502830 [ 22 ] {} <Trace> StorageKafka (event_1): Stalled
2019.08.26 10:24:12.504610 [ 22 ] {} <Trace> StorageKafka (event_1): Committed offset 20 (topic: test.event_1, partition: 0)                                                                                      
2019.08.26 10:24:12.505542 [ 22 ] {} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2019.08.26 10:24:12.507072 [ 22 ] {} <Trace> default.event_1_crm: Renaming temporary part tmp_insert_20190826_253_253_0 to 20190826_253_253_0.                                                                    
2019.08.26 10:24:12.507406 [ 22 ] {} <Trace> StorageKafka (event_1): Execution took 1006 ms.
2019.08.26 10:24:13.007686 [ 14 ] {} <Debug> StorageKafka (event_1): Started streaming to 1 attached views                                                                                                        
2019.08.26 10:24:13.008550 [ 14 ] {} <Trace> StorageKafka (event_1): Subscribed to topics: test.event_1
2019.08.26 10:24:13.008758 [ 14 ] {} <Trace> StorageKafka (event_1): Assigned to topics: test.event_1
2019.08.26 10:24:13.509399 [ 14 ] {} <Trace> StorageKafka (event_1): Polled batch of 10 messages
2019.08.26 10:24:14.009829 [ 14 ] {} <Trace> StorageKafka (event_1): Stalled
2019.08.26 10:24:14.011669 [ 14 ] {} <Trace> StorageKafka (event_1): Committed offset 20 (topic: test.event_1, partition: 0)                                                                                      
2019.08.26 10:24:14.012662 [ 14 ] {} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2019.08.26 10:24:14.014180 [ 14 ] {} <Trace> default.event_1_crm: Renaming temporary part tmp_insert_20190826_254_254_0 to 20190826_254_254_0.                                                                    
2019.08.26 10:24:14.014495 [ 14 ] {} <Trace> StorageKafka (event_1): Execution took 1006 ms.
2019.08.26 10:24:14.015715 [ 37 ] {} <Debug> default.event_1_crm (MergerMutator): Selected 6 parts from 20190826_1_249_49 to 20190826_254_254_0                                                                   
2019.08.26 10:24:14.015849 [ 37 ] {} <Debug> default.event_1_crm (MergerMutator): Merging 6 parts: from 20190826_1_249_49 to 20190826_254_254_0 into tmp_merge_20190826_1_254_50                                  
2019.08.26 10:24:14.016377 [ 37 ] {} <Debug> default.event_1_crm (MergerMutator): Selected MergeAlgorithm: Horizontal   
```

**Comment by filimonov** [comment]
@bl17zar what is your version?
There was an awful bug with infinite consuming of Kafka messages fixed recently: #6308

**Comment by bl17zar** [comment]
@filimonov how can I easily check it without clickhouse-client? I use latest tag from this docker image https://hub.docker.com/r/yandex/clickhouse-server and run clickhouse with this command for dev purposes 
```
docker run --network='host' -d --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server
```

**Comment by filimonov** [comment]
@bl17zar 
Try:
```
docker exec some-clickhouse-server clickhouse server --version
```

**Comment by bespilotnayakartoshka** [comment]
@filimonov  

```
CREATE TABLE my_table_with_kafka_engine
          ON CLUSTER my_cluster
          (some_schema)
        ENGINE = Kafka
        SETTINGS
          kafka_broker_list = 'some_host',
          kafka_topic_list = 'some_topic',
          kafka_group_name = 'some_group',
          kafka_format = 'JSONEachRow'

CREATE MATERIALIZED VIEW my_mv_consumer 
       ON CLUSTER my_cluster
        TO my_table
        AS SELECT *
        FROM my_table_with_kafka_engine

CREATE TABLE my_table 
ON CLUSTER my_cluster
(some_schema)
ENGINE ReplicatedMergreTree(...)

```

logs: 

```
2019.08.20 12:18:21.084695 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 65 messages
2019.08.20 12:18:21.084995 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297277
2019.08.20 12:18:21.585421 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 71 messages
2019.08.20 12:18:21.585727 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297348
2019.08.20 12:18:22.086062 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 68 messages
2019.08.20 12:18:22.086260 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297416
2019.08.20 12:18:22.586568 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 59 messages
2019.08.20 12:18:22.586750 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297475
2019.08.20 12:18:23.087081 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 55 messages
2019.08.20 12:18:23.087288 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297530
2019.08.20 12:18:23.419531 [ 11 ] {} <Debug> my_cluster.my_table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000004743 - log-0000004743
2019.08.20 12:18:23.422835 [ 11 ] {} <Debug> my_cluster.my_table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.08.20 12:18:23.425668 [ 33 ] {} <Debug> my_cluster.my_table: Fetching part 1453420800_18_18_0 from /clickhouse/tables/env/0/my_table/replicas/some_ip
2019.08.20 12:18:23.429240 [ 33 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://some_ip:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fenv%2F0%2Fmy_table%2Freplicas%2Fsome_ip&part=1453420800_18_18_0&compress=false
2019.08.20 12:18:23.440604 [ 33 ] {} <Trace> my_cluster.my_table: Renaming temporary part tmp_fetch_1453420800_18_18_0 to 1453420800_18_18_0.
2019.08.20 12:18:23.448247 [ 33 ] {} <Debug> my_cluster.my_table: Fetched part 1453420800_18_18_0 from /clickhouse/tables/env/0/my_table/replicas/some_ip
2019.08.20 12:18:23.587665 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 71 messages
2019.08.20 12:18:23.587966 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297601
2019.08.20 12:18:24.088393 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 67 messages
2019.08.20 12:18:24.088787 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297668
2019.08.20 12:18:24.589226 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 69 messages
2019.08.20 12:18:24.589558 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297737
2019.08.20 12:18:25.089886 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 64 messages
2019.08.20 12:18:25.090074 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297801
2019.08.20 12:18:25.590447 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 40 messages
2019.08.20 12:18:25.590660 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297841
2019.08.20 12:18:25.938047 [ 15 ] {} <Debug> my_cluster.my_table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000004744 - log-0000004744
2019.08.20 12:18:25.942612 [ 15 ] {} <Debug> my_cluster.my_table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.08.20 12:18:25.947301 [ 32 ] {} <Debug> my_cluster.my_table: Fetching part 1453420800_19_19_0 from /clickhouse/tables/env/0/my_table/replicas/some_ip
2019.08.20 12:18:25.948978 [ 32 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://some_ip:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fenv%2F0%2Fmy_table%2Freplicas%2Fsome_ip&part=1453420800_19_19_0&compress=false
2019.08.20 12:18:25.961543 [ 32 ] {} <Trace> my_cluster.my_table: Renaming temporary part tmp_fetch_1453420800_19_19_0 to 1453420800_19_19_0.
2019.08.20 12:18:25.967796 [ 32 ] {} <Debug> my_cluster.my_table: Fetched part 1453420800_19_19_0 from /clickhouse/tables/env/0/my_table/replicas/some_ip
2019.08.20 12:18:26.091001 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 16 messages
2019.08.20 12:18:26.091129 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297857
2019.08.20 12:18:26.591490 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 67 messages
2019.08.20 12:18:26.591783 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297924
2019.08.20 12:18:27.092199 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 65 messages
2019.08.20 12:18:27.092491 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297928
2019.08.20 12:18:27.093690 [ 22 ] {} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2019.08.20 12:18:27.099307 [ 22 ] {} <Debug> my_cluster.my_table (Replicated OutputStream): Wrote block with ID '1453420800_7379172606331902019_3151836889474142944', 930 rows
2019.08.20 12:18:27.104246 [ 22 ] {} <Trace> my_cluster.my_table: Renaming temporary part tmp_insert_1453420800_2006_2006_0 to 1453420800_20_20_0.
2019.08.20 12:18:27.108803 [ 21 ] {} <Debug> my_cluster.my_table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000004745 - log-0000004745
2019.08.20 12:18:27.111846 [ 22 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Execution took 8031 ms.
2019.08.20 12:18:27.112789 [ 21 ] {} <Debug> my_cluster.my_table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.08.20 12:18:27.117116 [ 54 ] {} <Trace> InterserverIOHTTPHandler-factory: HTTP Request for InterserverIOHTTPHandler-factory. Method: POST, Address: some_ip:56162, User-Agent: none, Content Type: , Transfer Encoding: identity
2019.08.20 12:18:27.117334 [ 54 ] {} <Trace> InterserverIOHTTPHandler: Request URI: /?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fenv%2F0%2Fmy_table%2Freplicas%2F178.62.188.183&part=1453420800_20_20_0&compress=false
2019.08.20 12:18:27.117422 [ 54 ] {} <Trace> my_cluster.my_table (Replicated PartsService): Sending part 1453420800_20_20_0
2019.08.20 12:18:27.122223 [ 54 ] {} <Information> InterserverIOHTTPHandler: Done processing query
2019.08.20 12:18:27.612006 [ 16 ] {} <Debug> StorageKafka (my_table_with_kafka_engine): Started streaming to 1 attached views
2019.08.20 12:18:27.612809 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1297989
2019.08.20 12:18:28.113204 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 119 messages
2019.08.20 12:18:28.113521 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298108
2019.08.20 12:18:28.613969 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 58 messages
2019.08.20 12:18:28.614387 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298166
2019.08.20 12:18:29.115011 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 63 messages
2019.08.20 12:18:29.115331 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298229
2019.08.20 12:18:29.615717 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 63 messages
2019.08.20 12:18:29.616006 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298292
2019.08.20 12:18:30.116387 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 18 messages
2019.08.20 12:18:30.116549 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298310
2019.08.20 12:18:30.616908 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 41 messages
2019.08.20 12:18:30.617219 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298351
2019.08.20 12:18:31.117684 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 60 messages
2019.08.20 12:18:31.118142 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298411
2019.08.20 12:18:31.618638 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 62 messages
2019.08.20 12:18:31.619291 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298473
2019.08.20 12:18:32.119765 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 62 messages
2019.08.20 12:18:32.120091 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298535
2019.08.20 12:18:32.620468 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 72 messages
2019.08.20 12:18:32.620787 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298607
2019.08.20 12:18:33.121273 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 67 messages
2019.08.20 12:18:33.121571 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298674
2019.08.20 12:18:33.621978 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 47 messages
2019.08.20 12:18:33.622265 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298721
2019.08.20 12:18:33.968156 [ 21 ] {} <Debug> my_cluster.my_table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000004746 - log-0000004746
2019.08.20 12:18:33.973796 [ 21 ] {} <Debug> my_cluster.my_table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.08.20 12:18:33.977439 [ 43 ] {} <Debug> my_cluster.my_table: Fetching part 1453420800_21_21_0 from /clickhouse/tables/env/0/my_table/replicas/some_ip
2019.08.20 12:18:33.977936 [ 43 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://some_ip:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fenv%2F0%2Fmy_table%2Freplicas%2Fsome_ip&part=1453420800_21_21_0&compress=false
2019.08.20 12:18:33.988241 [ 43 ] {} <Trace> my_cluster.my_table: Renaming temporary part tmp_fetch_1453420800_21_21_0 to 1453420800_21_21_0.
2019.08.20 12:18:33.994744 [ 43 ] {} <Debug> my_cluster.my_table: Fetched part 1453420800_21_21_0 from /clickhouse/tables/env/0/my_table/replicas/some_ip
2019.08.20 12:18:34.002184 [ 7 ] {} <Debug> my_cluster.my_table (MergerMutator): Selected 6 parts from 1453420800_0_16_2 to 1453420800_21_21_0
2019.08.20 12:18:34.010591 [ 10 ] {} <Debug> my_cluster.my_table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000004747 - log-0000004747
2019.08.20 12:18:34.013699 [ 10 ] {} <Debug> my_cluster.my_table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.08.20 12:18:34.013899 [ 38 ] {} <Trace> my_cluster.my_table: Executing log entry to merge parts 1453420800_0_16_2, 1453420800_17_17_0, 1453420800_18_18_0, 1453420800_19_19_0, 1453420800_20_20_0, 1453420800_21_21_0 to 1453420800_0_21_3
2019.08.20 12:18:34.013971 [ 38 ] {} <Debug> my_cluster.my_table (MergerMutator): Merging 6 parts: from 1453420800_0_16_2 to 1453420800_21_21_0 into tmp_merge_1453420800_0_21_3
2019.08.20 12:18:34.015241 [ 38 ] {} <Debug> my_cluster.my_table (MergerMutator): Selected MergeAlgorithm: Horizontal
2019.08.20 12:18:34.015382 [ 38 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 2 marks from part 1453420800_0_16_2, total 11103 rows starting from the beginning of the part, columns: some_columns
2019.08.20 12:18:34.016626 [ 38 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 1453420800_17_17_0, total 152 rows starting from the beginning of the part, columns: some_columns
2019.08.20 12:18:34.017927 [ 38 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 1453420800_18_18_0, total 870 rows starting from the beginning of the part, columns: some_columns
2019.08.20 12:18:34.022772 [ 38 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 1453420800_19_19_0, total 322 rows starting from the beginning of the part, columns: some_columns
2019.08.20 12:18:34.024049 [ 38 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 1453420800_20_20_0, total 930 rows starting from the beginning of the part, columns: some_columns
2019.08.20 12:18:34.025171 [ 38 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 1453420800_21_21_0, total 880 rows starting from the beginning of the part, columns: some_columns
2019.08.20 12:18:34.070081 [ 38 ] {} <Debug> MergingSortedBlockInputStream: Merge sorted 2 blocks, 14257 rows in 0.04 sec., 324015.00 rows/sec., 60.04 MB/sec.
2019.08.20 12:18:34.070216 [ 38 ] {} <Debug> my_cluster.my_table (MergerMutator): Merge sorted 14257 rows, containing 19 columns (19 merged, 0 gathered) in 0.06 sec., 253491.05 rows/sec., 46.97 MB/sec.
2019.08.20 12:18:34.075485 [ 38 ] {} <Trace> my_cluster.my_table: Renaming temporary part tmp_merge_1453420800_0_21_3 to 1453420800_0_21_3.
2019.08.20 12:18:34.075646 [ 38 ] {} <Trace> my_cluster.my_table (MergerMutator): Merged 6 parts: from 1453420800_0_16_2 to 1453420800_21_21_0
2019.08.20 12:18:34.123004 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 13 messages
2019.08.20 12:18:34.123165 [ 16 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Committing message with offset 1298734
``` 

there are 20k dups for 250k uniq records 
image: yandex/clickhouse-server:latest

**Comment by bl17zar** [comment]
@filimonov Thanks for the info on checking version. I ran the command and got the following response:
```
docker exec some-clickhouse-server clickhouse server --version
```

**Comment by filimonov** [comment]
@bl17zar unfortunately you have a buggy version. :\ Please update to 19.13.3

**Comment by filimonov** [comment]
@bespilotnayakartoshka your case sounds different. Please collect / provide more details.

**Comment by bl17zar** [comment]
@filimonov Thanks, I will update and come with results.

**Comment by bespilotnayakartoshka** [comment]
@filimonov sorry, i was sending to you a wrong log :< . 

```
2019.08.26 12:36:53.022008 [ 20 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 2234 messages
2019.08.26 12:36:53.529912 [ 20 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 4471 messages
2019.08.26 12:36:53.658857 [ 51 ] {d033d780-6280-4b2a-807f-4eeb10e0c81a} <Debug> executeQuery: (from 172.18.0.3:59058) INSERT INTO kek.my_table (columns) VALUES
2019.08.26 12:36:53.667657 [ 51 ] {d033d780-6280-4b2a-807f-4eeb10e0c81a} <Debug> kek.my_table (Replicated OutputStream): Wrote block with ID '1437091200_4318134954145958110_8825108836554034760', 4458 rows
2019.08.26 12:36:53.670550 [ 51 ] {d033d780-6280-4b2a-807f-4eeb10e0c81a} <Trace> kek.my_table: Renaming temporary part tmp_insert_1437091200_118_118_0 to 1437091200_13_13_0.
2019.08.26 12:36:53.674523 [ 51 ] {d033d780-6280-4b2a-807f-4eeb10e0c81a} <Debug> MemoryTracker: Peak memory usage (for query): 41.15 MiB.
2019.08.26 12:36:53.674645 [ 51 ] {d033d780-6280-4b2a-807f-4eeb10e0c81a} <Debug> MemoryTracker: Peak memory usage (total): 41.15 MiB.
2019.08.26 12:36:53.674690 [ 51 ] {d033d780-6280-4b2a-807f-4eeb10e0c81a} <Information> TCPHandler: Processed in 0.016 sec.
2019.08.26 12:36:53.677395 [ 18 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000000195 - log-0000000195
2019.08.26 12:36:53.679615 [ 18 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.08.26 12:36:53.684906 [ 55 ] {} <Trace> InterserverIOHTTPHandler-factory: HTTP Request for InterserverIOHTTPHandler-factory. Method: POST, Address: 172.18.0.4:59688, User-Agent: none, Content Type: , Transfer Encoding: identity
2019.08.26 12:36:53.684970 [ 55 ] {} <Trace> InterserverIOHTTPHandler: Request URI: /?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fdevelopment%2F01%2Fmy_table%2Freplicas%2Fclickhouse-01&part=1437091200_13_13_0&compress=false
2019.08.26 12:36:53.684997 [ 55 ] {} <Trace> kek.my_table (Replicated PartsService): Sending part 1437091200_13_13_0
2019.08.26 12:36:53.688981 [ 55 ] {} <Information> InterserverIOHTTPHandler: Done processing query
2019.08.26 12:36:54.032376 [ 7 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000000196 - log-0000000196
2019.08.26 12:36:54.035442 [ 7 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.08.26 12:36:54.037364 [ 41 ] {} <Debug> kek.my_table: Fetching part 1437091200_14_14_0 from /clickhouse/tables/development/01/my_table/replicas/clickhouse-04
2019.08.26 12:36:54.038395 [ 41 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://clickhouse-04:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fdevelopment%2F01%2Fmy_table%2Freplicas%2Fclickhouse-04&part=1437091200_14_14_0&compress=false
2019.08.26 12:36:54.041482 [ 20 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 2231 messages
2019.08.26 12:36:54.046262 [ 41 ] {} <Trace> kek.my_table: Renaming temporary part tmp_fetch_1437091200_14_14_0 to 1437091200_14_14_0.
2019.08.26 12:36:54.055253 [ 41 ] {} <Debug> kek.my_table: Fetched part 1437091200_14_14_0 from /clickhouse/tables/development/01/my_table/replicas/clickhouse-04
2019.08.26 12:36:54.286768 [ 58 ] {ff5ab413-b690-471f-af9c-8cf1a96f7d0f} <Debug> executeQuery: (from 172.18.0.6:43818) INSERT INTO kek.my_table (columns) VALUES
2019.08.26 12:36:54.294182 [ 58 ] {ff5ab413-b690-471f-af9c-8cf1a96f7d0f} <Debug> kek.my_table (Replicated OutputStream): Wrote block with ID '1437091200_15239424912367984940_11709965116278683804', 3345 rows
2019.08.26 12:36:54.302828 [ 58 ] {ff5ab413-b690-471f-af9c-8cf1a96f7d0f} <Trace> kek.my_table: Renaming temporary part tmp_insert_1437091200_119_119_0 to 1437091200_15_15_0.
2019.08.26 12:36:54.305351 [ 58 ] {ff5ab413-b690-471f-af9c-8cf1a96f7d0f} <Debug> MemoryTracker: Peak memory usage (for query): 40.53 MiB.
2019.08.26 12:36:54.305469 [ 58 ] {ff5ab413-b690-471f-af9c-8cf1a96f7d0f} <Debug> MemoryTracker: Peak memory usage (total): 40.53 MiB.
2019.08.26 12:36:54.305513 [ 58 ] {ff5ab413-b690-471f-af9c-8cf1a96f7d0f} <Information> TCPHandler: Processed in 0.019 sec.
2019.08.26 12:36:54.307901 [ 17 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000000197 - log-0000000197
2019.08.26 12:36:54.310897 [ 17 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.08.26 12:36:54.320454 [ 59 ] {} <Trace> InterserverIOHTTPHandler-factory: HTTP Request for InterserverIOHTTPHandler-factory. Method: POST, Address: 172.18.0.4:59700, User-Agent: none, Content Type: , Transfer Encoding: identity
2019.08.26 12:36:54.320529 [ 59 ] {} <Trace> InterserverIOHTTPHandler: Request URI: /?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fdevelopment%2F01%2Fmy_table%2Freplicas%2Fclickhouse-01&part=1437091200_15_15_0&compress=false
2019.08.26 12:36:54.320561 [ 59 ] {} <Trace> kek.my_table (Replicated PartsService): Sending part 1437091200_15_15_0
2019.08.26 12:36:54.325359 [ 59 ] {} <Information> InterserverIOHTTPHandler: Done processing query
2019.08.26 12:36:54.351795 [ 19 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000000198 - log-0000000198
2019.08.26 12:36:54.359710 [ 19 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.08.26 12:36:54.359865 [ 30 ] {} <Trace> kek.my_table: Executing log entry to merge parts 1437091200_0_10_2, 1437091200_11_11_0, 1437091200_12_12_0, 1437091200_13_13_0, 1437091200_14_14_0, 1437091200_15_15_0 to 1437091200_0_15_3
2019.08.26 12:36:54.359951 [ 30 ] {} <Debug> kek.my_table (MergerMutator): Merging 6 parts: from 1437091200_0_10_2 to 1437091200_15_15_0 into tmp_merge_1437091200_0_15_3
2019.08.26 12:36:54.361479 [ 30 ] {} <Debug> kek.my_table (MergerMutator): Selected MergeAlgorithm: Horizontal
2019.08.26 12:36:54.361551 [ 30 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 7 marks from part 1437091200_0_10_2, total 47372 rows starting from the beginning of the part, columns: columns
2019.08.26 12:36:54.362508 [ 30 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 2 marks from part 1437091200_11_11_0, total 4910 rows starting from the beginning of the part, columns: columns
2019.08.26 12:36:54.363393 [ 30 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 2 marks from part 1437091200_12_12_0, total 3351 rows starting from the beginning of the part, columns: columns
2019.08.26 12:36:54.364590 [ 30 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 2 marks from part 1437091200_13_13_0, total 4458 rows starting from the beginning of the part, columns: columns
2019.08.26 12:36:54.365463 [ 30 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 2 marks from part 1437091200_14_14_0, total 3342 rows starting from the beginning of the part, columns: columns
2019.08.26 12:36:54.366407 [ 30 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 2 marks from part 1437091200_15_15_0, total 3345 rows starting from the beginning of the part, columns: columns
2019.08.26 12:36:54.433384 [ 30 ] {} <Debug> kek.my_table (MergerMutator): Merge sorted 66778 rows, containing 20 columns (20 merged, 0 gathered) in 0.07 sec., 909443.76 rows/sec., 171.13 MB/sec.
2019.08.26 12:36:54.437050 [ 30 ] {} <Trace> kek.my_table: Renaming temporary part tmp_merge_1437091200_0_15_3 to 1437091200_0_15_3.
2019.08.26 12:36:54.437166 [ 30 ] {} <Trace> kek.my_table (MergerMutator): Merged 6 parts: from 1437091200_0_10_2 to 1437091200_15_15_0
2019.08.26 12:36:54.546624 [ 20 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 2230 messages
2019.08.26 12:36:55.053208 [ 20 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 2233 messages
2019.08.26 12:36:55.558184 [ 20 ] {} <Trace> StorageKafka (my_table_with_kafka_engine): Polled batch of 2233 messages
2019.08.26 12:36:55.606245 [ 6 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000000199 - log-0000000199
2019.08.26 12:36:55.610182 [ 6 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.08.26 12:36:55.616888 [ 42 ] {} <Debug> kek.my_table: Fetching part 1437091200_16_16_0 from /clickhouse/tables/development/01/my_table/replicas/clickhouse-04
2019.08.26 12:36:55.617796 [ 42 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://clickhouse-04:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fdevelopment%2F01%2Fmy_table%2Freplicas%2Fclickhouse-04&part=1437091200_16_16_0&compress=false
2019.08.26 12:36:55.623762 [ 42 ] {} <Trace> kek.my_table: Renaming temporary part tmp_fetch_1437091200_16_16_0 to 1437091200_16_16_0.
2019.08.26 12:36:55.634946 [ 42 ] {} <Debug> kek.my_table: Fetched part 1437091200_16_16_0 from /clickhouse/tables/development/01/my_table/replicas/clickhouse-04
2019.08.26 12:36:55.832150 [ 18 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000000200 - log-0000000200
2019.08.26 12:36:55.834058 [ 18 ] {} <Debug> kek.my_table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.08.26 12:36:55.838055 [ 29 ] {} <Debug> kek.my_table: Fetching part 1437091200_17_17_0 from /clickhouse/tables/development/01/my_table/replicas/clickhouse-04
2019.08.26 12:36:55.838940 [ 29 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://clickhouse-04:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fdevelopment%2F01%2Fmy_table%2Freplicas%2Fclickhouse-04&part=1437091200_17_17_0&compress=false
2019.08.26 12:36:55.845072 [ 29 ] {} <Trace> kek.my_table: Renaming temporary part tmp_fetch_1437091200_17_17_0 to 1437091200_17_17_0.
2019.08.26 12:36:55.855155 [ 29 ] {} <Debug> kek.my_table: Fetched part 1437091200_17_17_0 from /clickhouse/tables/development/01/my_table/replicas/clickhouse-04
```

```
SELECT version()
│ 19.13.3.26 │
```

docker  `image: yandex/clickhouse-server:19.13`. reproduced on 19.11 also 

current schema on each instance: 

```
kafka engine -> MV -> target table 
``` 

current difference: 

```
select count(*), countDistinct(*) from my_distributed_table 

 597511, 575207 
``` 

also almost the same result on local tables

**Comment by bl17zar** [comment]
@filimonov After I changed the version to 19.13.3.26 everything works as expected.

**Comment by filimonov** [comment]
> @filimonov After I changed the version to 19.13.3.26 everything works as expected.
Thank you for the feedback

@bespilotnayakartoshka unfortunatelly that information is not enough to reproduce the problem. 
Please describe your setup. How many CH nodes, how many Kafka brokers, how many partitions in topic, kafka settings (if some non standard are used) and if possible - create table statements.

**Comment by bespilotnayakartoshka** [comment]
@filimonov  

So. I have 2 shards with 2 replicas each with current table setup: 

```
 CREATE TABLE my_super_table ON CLUSTER my_cluster
        (some_id         UInt64,
         .... 
         created_at DateTime)
        ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/balance_transactions', '{replica}')
      PARTITION BY toStartOfDay(toDate(created_at))
```

```
CREATE TABLE my_super_table_all
        ON CLUSTER my_cluster
        AS my_super_table
        ENGINE = Distributed(my_cluster, my_db, my_super_table, modulo(some_id, 2))
```

This is the kafka flow setup: 

```
 CREATE TABLE my_super_table_queue
          ON CLUSTER my_cluster
          (some_id Uint64, 
             ..... 
           )
        ENGINE = Kafka
        SETTINGS
          kafka_broker_list = 'localhost:9093',
          kafka_topic_list = 'my_topic_name',
          kafka_group_name = 'my_group_name',
          kafka_format = 'JSONEachRow'
```

```
 CREATE MATERIALIZED VIEW my_super_table_consumer
        ON CLUSTER my_cluster
        TO my_super_table_all
        AS SELECT *
        FROM my_super_table_queue
```

So, as you see i have 4 CH nodes with single kafka broker which has 4 partitions for each topic. 
Kafka version is 2.2.0.

Kafka table -> MV -> Dist table -> Target table. In simple way. 

During push something to kafka, for example, 10kk messages sometimes i have a dups randomly appears on both shards or single shard(both instances on single shard has dups). 

Simple example (first number is number of shard, second one is number of replica) when i pushed simple 10 numbers from 1 to 10 in kafka: 

`1-1`: 1-2-2-3-4-5
`1-2`: 1-2-3-4-5

`2-1`: 5-6-7-8-9-10
`2-2`: 5-6-7-8-9-10

And if we try to make some select: 

```
select count(*), countDistinct(*) from distirbuted_table;

=> 12, 10 | the dups are `2` on first shard and `5` on both shards
``` 

I tried to explain as much as i can my case, if there are still not enough info i will try to add more. Thanks :)

**Comment by bespilotnayakartoshka** [comment]
@filimonov up 

on 19.13.3.26 it like 50% of dups

**Comment by den-crane** [comment]
@bespilotnayakartoshka It's very unusual to use Distributed tables in this workflow.

Can you show my_cluster description? Are you sure you used `<internal_replication>true</internal_replication>` and Distributed is not the root cause of the issue?

**Comment by filimonov** [comment]
> @filimonov up
> 
> on 19.13.3.26 it like 50% of dups

@bespilotnayakartoshka Can you try on 19.11.9 (it has important Kafka fixes)?
 Also what's about @den-crane question?

**Comment by arruzk** [comment]
It's still reproducing in version `19.14.6.12`. I inserted data directly to the table with `Kafka` engine and got almost 50% of duplicates
```
select count(*), countDistinct(*) 
41549936	19716621
```

**Comment by romankos** [comment]
Temporary solution for preventing duplicates - to use only 1 consumer:
kafka_num_consumers = 1
But this strange situation with duplicates must be solved on ClickHouse side.

**Comment by arruzk** [comment]
@romankos it doesn't work(
Still the same ~50% of duplicates (`41549936`)

**Comment by romankos** [comment]
> @romankos it doesn't work(
> Still the same ~50% of duplicates (`41549936`)

This solution prevent only new duplicates.
For already exists duplicates you can use DISTINCT in queries or remove duplicated records via "alter table delete"

**Comment by arruzk** [comment]
@romankos yes, I truncated table before running a new test.
Maybe we are talking about slightly different problems. I'm inserting data (of course different than in Kafka topic) to the table with `Kafka` engine directly (https://github.com/ClickHouse/ClickHouse/issues/5834 it was added in version 19.14.3.3). Consumers working just fine (even with 3 consumers)

**Comment by abyss7** [comment]
The reason behind this behavior is trivial. When we insert into Kafka table, the MV pushes new rows to corresponding tables (standard CH feature), but then the same MV reads these messages from Kafka server and pushes them second time.

Is it good enough for you to have separate Kafka tables? Does it break your scenarios?

**Comment by arruzk** [comment]
@abyss7 during my tests Kafka topic didn't contain the same data as I inserted manually. It's not a big problem for me, I just used temporary table (insert in a temporary table and move data manually) in my scenario, just wanted to avoid one intermediate step.

**Comment by filimonov** [comment]
> @abyss7 during my tests Kafka topic didn't contain the same data as I inserted manually. It's not a big problem for me, I just used temporary table (insert in a temporary table and move data manually) in my scenario, just wanted to avoid one intermediate step.

Can you describe the exact steps with expected and real results?

**Comment by romankos** [comment]
@abyss7 But at the moment we have  19.15.2.2, 2019-10-01 version
