### ISSUE TITLE
Ubantu build clickhouse failed in arm version

### ISSUE THREAD

**Issue by helloboy1234** [yandex/ClickHouse#6721]
clichouse source code version: v19.13.3.26-stable
ubantu for arm version: 18.04
gcc versioin:8.3.0
ninja version: 1.8.2-1
cmake version:3.11.2

build failed，Details are as follows：

during RTL pass: expand
In file included from ../dbms/src/Functions/bitRotateRight.cpp:2:
../dbms/src/Functions/FunctionBinaryArithmetic.h: In static member function ‘static void DB::BinaryOperationImplBase<A, B, Op, ResultType_>::vector_constant(DB::PaddedPODArray<T>&, B, DB::PaddedPODArray<ResultType_>&) [with A = unsigned char; B = long unsigned int; Op = DB::BitRotateRightImpl<unsigned char, long unsigned int>; ResultType_ = long unsigned int]’:
../dbms/src/Functions/FunctionBinaryArithmetic.h:72:13: internal compiler error: in expand_shift_1, at expmed.c:2631
             c[i] = Op::template apply<ResultType>(a[i], b);

**Comment by akuzm** [comment]
'internal compiler error' means that it is a compiler bug. It should be reported to gcc according to their guidelines: https://www.gnu.org/software/gcc/bugs/

The only issue with the same error message I could find should be already fixed in gcc 8.3: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84853

**Comment by alexey-milovidov** [comment]
@helloboy1234 You can use gcc-9.

**Comment by helloboy1234** [comment]
OK，I'll try GCC-9. Thanks!




------------------ 原始邮件 ------------------
发件人: "alexey-milovidov"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 晚上7:05
收件人: "yandex/ClickHouse"<ClickHouse@noreply.github.com>;
抄送: "晴天"<408996957@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [yandex/ClickHouse] Ubantu build clickhouse failed in arm version(#6721)




@helloboy1234 You can use gcc-9.

**Comment by helloboy1234** [comment]
My compiler version is low?




------------------ 原始邮件 ------------------
发件人: "akuzm"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 晚上6:39
收件人: "yandex/ClickHouse"<ClickHouse@noreply.github.com>;
抄送: "晴天"<408996957@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yandex/ClickHouse] Ubantu build clickhouse failed in arm version(#6721)




'internal compiler error' means that it is a compiler bug. It should be reported to gcc according to their guidelines: https://www.gnu.org/software/gcc/bugs/
 
The only issue with the same error message I could find should be already fixed in gcc 8.3: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84853

**Comment by helloboy1234** [comment]
I still failed to compile with gcc-9,the error is the same as above.




------------------ 原始邮件 ------------------
发件人: "alexey-milovidov"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 晚上7:05
收件人: "yandex/ClickHouse"<ClickHouse@noreply.github.com>;
抄送: "晴天"<408996957@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [yandex/ClickHouse] Ubantu build clickhouse failed in arm version(#6721)




@helloboy1234 You can use gcc-9.

**Comment by alexey-milovidov** [comment]
You still can use clang (versions 9, 8, 7 will work).

**Comment by mybluecrab** [comment]
I used clang build ok on aarch64, but when I run the clickhouse-server , is locked. gdb info

#0  Poco::MutexImpl::lockImpl (this=0xffffe5703988) at /usr/include/Poco/Mutex_POSIX.h:59
#1  0x0000fffff67f3c44 in Poco::FastMutex::lock (this=0xffffe5703988)
    at /usr/include/Poco/Mutex.h:238
#2  Poco::ScopedLock<Poco::FastMutex>::ScopedLock (this=<optimized out>, mutex=...)
    at /usr/include/Poco/ScopedLock.h:38
#3  Poco::AtomicCounter::operator++ (this=0xffffe5703988)
    at /usr/include/Poco/AtomicCounter.h:360
#4  Poco::RefCountedObject::duplicate (this=0xffffe5703980)
    at /usr/include/Poco/RefCountedObject.h:74
#5  Poco::AutoPtr<Poco::Util::AbstractConfiguration>::assign (this=0xffffffffeb68, ptr=...)
    at /usr/include/Poco/AutoPtr.h:120
#6  Poco::AutoPtr<Poco::Util::AbstractConfiguration>::operator= (this=0xffffffffeb68, ptr=...)
    at /usr/include/Poco/AutoPtr.h:174
#7  0x0000ffffec556a38 in Poco::Util::LayeredConfiguration::add (this=0xffffe5703c80,
    pConfig=0xffffe5703980, label="", priority=100, writeable=false, shared=false)
    at src/LayeredConfiguration.cpp:119
#8  0x0000ffffec55698c in Poco::Util::LayeredConfiguration::add (this=0xffffe5703c80,
    pConfig=0xffffe5703980, priority=100, writeable=false, shared=false)
    at src/LayeredConfiguration.cpp:112
#9  0x0000ffffec548bf8 in Poco::Util::Application::setup (this=0xffffffffed78)
    at src/Application.cpp:100
#10 0x0000ffffec548778 in Poco::Util::Application::Application (this=0xffffffffed78)
    at src/Application.cpp:74
#11 0x0000ffffec566d60 in Poco::Util::ServerApplication::ServerApplication (
    this=0xffffffffed78) at src/ServerApplication.cpp:71
#12 0x0000fffff4729ff8 in BaseDaemon::BaseDaemon (this=0xffffffffed78)
    at ../libs/libdaemon/src/BaseDaemon.cpp:320
#13 0x0000fffff42f5c54 in DB::Server::Server (this=0xffffffffed78)
    at ../dbms/programs/server/Server.h:21
#14 mainEntryClickHouseServer (argc=1, argv=0xffffe7100710)
    at ../dbms/programs/server/Server.cpp:959
#15 0x0000000000265270 in main (argc_=<optimized out>, argv_=<optimized out>)
    at ../dbms/programs/main.cpp:178

**Comment by wk198803** [comment]
> clichouse source code version: v19.13.3.26-stable
> ubantu for arm version: 18.04
> gcc versioin:8.3.0
> ninja version: 1.8.2-1
> cmake version:3.11.2
> 
> build failed，Details are as follows：
> 
> during RTL pass: expand
> In file included from ../dbms/src/Functions/bitRotateRight.cpp:2:
> ../dbms/src/Functions/FunctionBinaryArithmetic.h: In static member function ‘static void DB::BinaryOperationImplBase<A, B, Op, ResultType_>::vector_constant(DB::PaddedPODArray&, B, DB::PaddedPODArray<ResultType_>&) [with A = unsigned char; B = long unsigned int; Op = DB::BitRotateRightImpl<unsigned char, long unsigned int>; ResultType_ = long unsigned int]’:
> ../dbms/src/Functions/FunctionBinaryArithmetic.h:72:13: internal compiler error: in expand_shift_1, at expmed.c:2631
> c[i] = Op::template apply(a[i], b);

i have the question, did u solve that?
